### ISSUE TITLE
Incorrect labels in the app (percentiles of Binomial distribution)

### ISSUE THREAD

**Issue by GegznaV** [rsquaredacademy/descriptr#45]
In the app, labels "Aggregated probability" and "Probability of success" are swapped and this issue should be corrected. Find more details in the screenshot:

![image](https://user-images.githubusercontent.com/12725868/38023673-a24d61ac-328b-11e8-8ac1-cedd644827ae.png)

**Comment by aravindhebbali** [comment]
![binom_bug](https://user-images.githubusercontent.com/8706536/38030534-83a7e6b6-32b6-11e8-9498-b9bc9cec1b00.png)
