### ISSUE TITLE
kable friendly output

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/descriptr#71]
Create `kable()` friendly output for the following:

- [ ] `ds_summary_stats()`
- [ ] `ds_screener()`
- [ ] `ds_cross_table()`
- [ ] `ds_freq_table()`
- [ ] `ds_freq_cont()`
- [ ] `ds_group_summary()`
- [ ] `ds_oway_tables()`
- [ ] `ds_tway_tables()`

**Comment by aravindhebbali** [comment]
Not a priority in 0.5.0

**Comment by GegznaV** [comment]
By stating "`knitr::kable()`-friendly" do you also mean "`pander::pander()`-friendly"?

**Comment by aravindhebbali** [comment]
> 
> 
> By stating "`knitr::kable()`-friendly" do you also mean "`pander::pander()`-friendly"?

Yes, that will be the main focus in the next release.
